name: Deploy lobby Service

on:
  push:
    paths:
      - "lobby-service/**"
      - ".github/workflows/lobby.yaml"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/lobby-service:latest ./lobby-service
          docker push ghcr.io/${{ github.repository_owner }}/lobby-service:latest

      # - name: Set up kubectl
      #   run: |
      #     echo "${{ secrets.KUBECONFIG }}" > kubeconfig
      #     export KUBECONFIG=./kubeconfig

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f lobby-service/k8s/